name: speech-and-audio-processing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.25.*
  - librosa=0.10.*
  - tensorflow=2.16.1
  - keras
  - pandas
  #- cudatoolkit=11.8 # Uncomment these lines if you have an NVIDIA GPU
  #- cudnn=8.6
  #- tensorrt # Uncomment if you intend to use TensorRT
